language: node_js
node_js:
  - '4.2'
install:
  - npm install hubot-ibmcloud-cogntive-lib
  - export HUBOT_DB_PATH=~/
  - travis_wait 30 npm install
script:
  - 'npm run lint'
  - 'npm run coverage'
notifications:
  slack: ${SLACK_TOKEN}
